# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e0e3d9197c91d866cbd6d400d873077473b4a6247632b2242c84f864b223323754e6bec7bcd12ea15fe733e8e2794bd30b7ab294402402520f9f73aea224d74

test:
  secret_key_base: 676793597b7ba469aa2ba8bf3205a17f295ccb89707b1bb1f0ede156409bac6151c998d1a9a44650809f09b9ffec96ee814b9e93366f72d193087ab56ef511d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
